export default {
  UNAUTHORIZED: "UNAUTHORIZED",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  DATA_UPDATE_FAILED: "DATA_UPDATE_FAILED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_TYPE: "INVALID_TYPE",
  ALREADY_EXIST: "ALREADY EXIST",
};
