export default {
  SUCCESSFULLY_AUTHORIZED: "SUCCESSFULLY_AUTHORIZED",
  SUCCESSFULLY_USER_CREATED: "SUCCESSFULLY_USER_CREATED",
  SUCCESSFULLY_USER_UPDATED: "SUCCESSFULLY_USER_UPDATED",
  SUCCESSFULLY_USER_DELETED: "SUCCESSFULLY_USER_DELETED",
  SUCCESSFULLY_DATA_RETRIEVED: "SUCCESSFULLY_DATA_RETRIEVED",
  SUCCESSFULLY_DATA_ADDED: "SUCCESSFULLY_DATA_ADDED",
  SUCCESSFULLY_DATA_UPDATED: "SUCCESSFULLY_DATA_UPDATED",
  SUCCESSFULLY_DATA_DELETED: "SUCCESSFULLY_DATA_DELETED",
};
